name: tasks_project
services:
  tasks_api:
    env_file:
      - ../.env
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: tasks_api
    ports:
      - "${API_PORT:-8000}:8000"
    restart: unless-stopped
    volumes:
      - ./src/db/db.db:/app/db/db.db

  frontend_tasks:
    build:
      context: ..
      dockerfile: ./frontend/docker/Dockerfile
    container_name: tasks_frontend
    env_file:
      - ../.env
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    restart: unless-stopped
    depends_on:
      - tasks_api