name: tasks_api
services:
  tasks_api:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: tasks_api
    ports:
      - "${API_PORT}:8000"
    restart: unless-stopped